project:
  type: website

website:
  title: "Rosihan Inc"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - about.qmd
      - icon: github
        href: https://github.com/naylarosihan
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

